apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlistservice
  labels:
    app: wishlistservice
spec:
  selector:
    matchLabels:
      app: wishlistservice
  template:
    metadata:
      labels:
        app: wishlistservice
    spec:
      serviceAccountName: wishlistservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: wishlistservice
        ports:
        - containerPort: 50052
        env:
        - name: PORT
          value: "50052"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          periodSeconds: 5
          grpc:
            port: 50052
        livenessProbe:
          periodSeconds: 5
          grpc:
            port: 50052
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: wishlistservice
  labels:
    app: wishlistservice
spec:
  type: NodePort
  selector:
    app: wishlistservice
  ports:
  - name: grpc
    port: 50052
    targetPort: 50052
    nodePort: 30007
# spec:
#   type: ClusterIP
#   selector:
#     app: wishlistservice
#   ports:
#   - name: grpc
#     port: 50052
#     targetPort: 50052
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wishlistservice