name: CI for Wishlist Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Code auschecken
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Python-Umgebung einrichten
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.0 

      -name: Navigate to the directory
        working-directory: ./src/wishlistservice
        run: pwd

      - name: Install dependencies
        working-directory: ./src//wishlistservice
        run: |
          python -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 3. Tests ausführen
      - name: Run tests
        working-directory: ./src/wishlistservice
        run: |
          . venv/bin/activate
          pytest

      # 4. Docker-Image bauen
      - name: Build Docker image
        run: echo "Build Docker image..."

      # Optional: Docker-Image testen (z.B. starten und prüfen)
      - name: Test Docker image
        run: echo "Test Docker image..."